/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.training.fooddelivery;

import org.assertj.core.api.ObjectArrayAssert;
import org.junit.jupiter.api.Test;
import org.assertj.core.api.AbstractObjectAssert;
class AppTest {
    @Test
    void appHasAGreeting() {

    }
}
